# Generated by Django 3.1.1 on 2020-09-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=100)),
                ('PFPJ', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1)),
                ('CPFCNPJ', models.CharField(max_length=20)),
                ('EMAIL1', models.CharField(blank=True, max_length=60, null=True)),
                ('EMAIL2', models.CharField(blank=True, max_length=60, null=True)),
                ('DATAHORACADASTRO', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
    ]
