# Generated by Django 3.1.1 on 2020-09-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scprag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALOR', models.FloatField()),
                ('DATAHORA', models.DateTimeField(auto_now=True)),
                ('COMPLEMENTO', models.CharField(max_length=200)),
                ('ID_LANCADOPOR', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Caixa',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.CharField(max_length=100, verbose_name='DESCRIÇÃO')),
                ('BANCO', models.IntegerField(blank=True, null=True)),
                ('AGENCIA', models.CharField(blank=True, max_length=15, null=True, verbose_name='AGÊNCIA')),
                ('CONTA', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Conta',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=100)),
                ('DEPARTAMENTO', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Contato',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATAINICIAL', models.DateTimeField(verbose_name='DATA INICIAL')),
                ('DATAFINAL', models.DateTimeField(verbose_name='DATA FINAL')),
                ('VALOR', models.FloatField(verbose_name='VALOR')),
                ('PERIODO', models.IntegerField(verbose_name='PERÍODO')),
            ],
            options={
                'db_table': 'Contrato',
            },
        ),
        migrations.CreateModel(
            name='FormadePagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.CharField(max_length=100, verbose_name='DESCRIÇÃO')),
            ],
            options={
                'db_table': 'FormaDePagamento',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=100)),
                ('EMAIL', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Funcionário',
            },
        ),
        migrations.CreateModel(
            name='HistoricoPadrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.CharField(max_length=100, verbose_name='DESCRIÇÃO')),
            ],
            options={
                'db_table': 'Historico_Padrão',
            },
        ),
        migrations.CreateModel(
            name='OsProposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATAHORACADASTRO', models.DateTimeField(auto_now=True)),
                ('CADASTRADOPOR', models.IntegerField(default=1)),
                ('TIPO', models.CharField(choices=[('P', 'PROPOSTA'), ('O', 'ORDEM DE SERVIÇO')], max_length=1)),
                ('DATAOS', models.DateField(editable=False)),
                ('VALORPROPOSTA', models.FloatField(verbose_name='VALOR DA PROPOSTA')),
                ('VALOROS', models.FloatField(verbose_name='VALOR DA ORDEM DE SERVIÇO')),
                ('DATAREFORCO', models.DateField(blank=True, null=True, verbose_name='DATA DO REFORÇO')),
            ],
            options={
                'db_table': 'OsProposta',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.CharField(max_length=100, verbose_name='DESCRIÇÃO')),
                ('UNIDADE', models.CharField(choices=[('UND', 'Unidade'), ('KG', 'Kilograma'), ('ML', 'Mililitros'), ('L', 'Litros'), ('UND', 'Unidade'), ('KG', 'Kilograma')], max_length=3, verbose_name='UNIDADE')),
                ('ESTOQUEMINIMO', models.IntegerField(verbose_name='ESTOQUE MÍNIMO')),
                ('INSTRUCOES', models.CharField(blank=True, max_length=200, null=True, verbose_name='INSTRUÇÕES DE PREPARO')),
                ('TIPO', models.CharField(choices=[('Equipamento', ''), ('Veneno', ''), ('Químico', ''), ('Diluente', '')], max_length=20, verbose_name='TIPO DE PRODUTO')),
            ],
            options={
                'db_table': 'Produto',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.CharField(max_length=100, verbose_name='DESCRIÇÃO')),
                ('RECOMENDACOES', models.CharField(blank=True, max_length=100, null=True, verbose_name='RECOMENDAÇÕES')),
                ('VALOR1', models.FloatField(verbose_name='VALOR 1')),
                ('VALOR2', models.FloatField(verbose_name='VALOR 2')),
                ('VALOR3', models.FloatField(verbose_name='VALOR 3')),
                ('DESCONTOPERMITIDO', models.FloatField(verbose_name='LIMITE PARA DESCONTO (%)')),
                ('LIMITEAREA', models.FloatField(verbose_name='LIMITE PARA ÁREA(m²)')),
                ('LIMITECOMPARTIMENTOS', models.IntegerField(verbose_name='NÚMERO MÁXIMO DE COMPARTIMENTOS')),
                ('GARANTIA', models.FloatField(verbose_name='GARANTIA (MESES)')),
                ('REFORCO', models.FloatField(verbose_name='MESES ATÉ O REFORÇO')),
                ('ContratoServico', models.ManyToManyField(to='scprag.Contrato')),
            ],
            options={
                'db_table': 'Serviço',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CPFCNPJ',
            field=models.CharField(max_length=20, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='PFPJ',
            field=models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1, verbose_name='FÍSICA OU JURÍDICA'),
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TELEFONE', models.CharField(max_length=20)),
                ('ID_CLIENTE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scprag.cliente', verbose_name='CLIENTE')),
                ('ID_CONTATO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scprag.contato', verbose_name='NOME DO CONTATO')),
                ('ID_FUNCIONARIO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scprag.funcionario', verbose_name='FUNCIONARIO')),
            ],
            options={
                'db_table': 'Telefone',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VENCIMENTO_ASO', models.DateField(verbose_name='DATA DE VENCIMENTO DA ASO')),
                ('ID_FUNCIONARIO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.funcionario', verbose_name='NOME DO FUNCIONÁRIO')),
                ('TecnicoServico', models.ManyToManyField(to='scprag.Servico')),
            ],
            options={
                'db_table': 'Técnico',
            },
        ),
        migrations.CreateModel(
            name='ServicoProdutoEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTD', models.FloatField(blank=True, null=True)),
                ('INSTRUCOES', models.CharField(max_length=200)),
                ('ID_PRODUTO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.produto', verbose_name='NOME DO EQUIPAMENTO/PRODUTO')),
                ('ID_SERVICO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.servico', verbose_name='SERVIÇO')),
            ],
            options={
                'db_table': 'ServiçoProdutoEquipamento',
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTD', models.FloatField(verbose_name='QUANTIDADE SAÍDA')),
                ('DATAHORA', models.DateTimeField(auto_now=True)),
                ('OBS', models.CharField(max_length=100)),
                ('ID_OsProposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scprag.osproposta', verbose_name='ORDEM DE SERVIÇO')),
                ('ID_PRODUTO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.produto', verbose_name='PRODUTO')),
            ],
            options={
                'db_table': 'Saída',
            },
        ),
        migrations.AddField(
            model_name='osproposta',
            name='ID_CLIENTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.cliente', verbose_name='CLIENTE'),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO', models.CharField(choices=[('Agenda', ''), ('Financeiro', ''), ('Tecnico', ''), ('OS', '')], max_length=20, verbose_name='TIPO DE MENSAGEM')),
                ('DATAENVIAR', models.DateTimeField(verbose_name='DATA A SER ENVIADA')),
                ('DATAENVIO', models.DateTimeField(blank=True, editable=False, null=True)),
                ('MEIO', models.CharField(choices=[('E-mail', ''), ('SMS', ''), ('Whatsapp', '')], max_length=20, verbose_name='MEIO DE ENVIO')),
                ('MENSAGEM', models.TextField()),
                ('ENDERECODESTINATARIO', models.CharField(max_length=100, verbose_name='ENDEREÇO DO DESTINATÁRIO')),
                ('CaixaMensagem', models.ManyToManyField(to='scprag.Caixa')),
                ('OsMensagem', models.ManyToManyField(to='scprag.OsProposta')),
                ('TecnicoMensagem', models.ManyToManyField(to='scprag.Tecnico')),
            ],
            options={
                'db_table': 'Mensagem',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEP', models.CharField(max_length=20)),
                ('LOGRADOURO', models.CharField(max_length=100)),
                ('NUMERO', models.CharField(max_length=10, verbose_name='NÚMERO')),
                ('REFERENCIA', models.CharField(blank=True, max_length=100, null=True, verbose_name='PONTO DE REFERÊNCIA')),
                ('COORDENADAS', models.CharField(blank=True, max_length=100, null=True, verbose_name='COORDENADAS DE LOCALIZAÇÃO')),
                ('AREA', models.CharField(blank=True, max_length=100, null=True, verbose_name='ÁREA TOTAL')),
                ('COMPARTIMENTOS', models.IntegerField(blank=True, null=True, verbose_name='NÚMERO DE COMPARTIMENTOS')),
                ('BANHEIROS', models.CharField(blank=True, max_length=100, null=True, verbose_name='NÚMERO DE BANHEIROS')),
                ('OBS', models.CharField(blank=True, max_length=200, null=True, verbose_name='OBSERVAÇÕES')),
                ('ID_CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.cliente', verbose_name='CLIENTE')),
            ],
            options={
                'db_table': 'Local',
            },
        ),
        migrations.CreateModel(
            name='EntregaProdutoEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATAHORA', models.DateTimeField(auto_now=True)),
                ('QTDENTREGUE', models.FloatField(verbose_name='QUANTIDADE ENTREGUE')),
                ('QTDDEVOLVIDA', models.FloatField(verbose_name='QUANTIDADE DEVOLVIDA')),
                ('OBS', models.CharField(max_length=200)),
                ('ID_PRODUTO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.produto', verbose_name='NOME DO PRODUTO')),
                ('ID_TECNICO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.tecnico', verbose_name='NOME DO TÉCNICO')),
            ],
            options={
                'db_table': 'EntregaProdutoEquipamento',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATAHORA', models.DateTimeField(auto_now=True)),
                ('QUANTIDADE', models.FloatField(verbose_name='QUANTIDADE ENTRADA')),
                ('ID_PRODUTO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.produto', verbose_name='PRODUTO')),
            ],
            options={
                'db_table': 'Entrada',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='ID_CLIENTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.cliente', verbose_name='CLIENTE'),
        ),
        migrations.AddField(
            model_name='contato',
            name='ID_CLIENTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.cliente', verbose_name='CLIENTE'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='ID_CONTA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.conta', verbose_name='CONTA'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='ID_FORMAPAG',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.formadepagamento'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='ID_HISTORICOPADRAO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scprag.historicopadrao', verbose_name='HISTÓRICO PADRÃO'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='ID_OSPROPOSTA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scprag.funcionario', verbose_name='ORDEM DE SERVIÇO'),
        ),
    ]
