# Generated by Django 3.1.1 on 2020-09-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scprag', '0002_auto_20200926_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='ContratoServico',
        ),
        migrations.AddField(
            model_name='contrato',
            name='ContratoServico',
            field=models.ManyToManyField(to='scprag.Servico'),
        ),
    ]
