# Generated by Django 3.1.1 on 2020-09-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scprag', '0003_auto_20200926_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='osproposta',
            name='OsPropostaServicos',
            field=models.ManyToManyField(to='scprag.Servico'),
        ),
    ]
