# Generated by Django 3.1.1 on 2020-09-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scprag', '0004_osproposta_ospropostaservicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osproposta',
            name='DATAOS',
            field=models.DateField(auto_now=True),
        ),
    ]
