# Generated by Django 3.1.1 on 2020-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scprag', '0005_auto_20200926_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='ID_CLIENTE',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='ID_CONTATO',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='ID_FUNCIONARIO',
        ),
        migrations.AddField(
            model_name='cliente',
            name='TELEFONE',
            field=models.ManyToManyField(to='scprag.Telefone'),
        ),
        migrations.AddField(
            model_name='contato',
            name='TELEFONE',
            field=models.ManyToManyField(to='scprag.Telefone'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='DATA_NASCIMENTO',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='TELEFONE',
            field=models.ManyToManyField(to='scprag.Telefone'),
        ),
    ]
