# Generated by Django 3.1.1 on 2020-10-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scprag', '0006_auto_20201007_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='DATA_NASCIMENTO',
            field=models.DateField(default='2000-01-12'),
            preserve_default=False,
        ),
    ]
