# Generated by Django 3.1.1 on 2020-10-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scprag', '0008_auto_20201020_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='BAIRRO',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='CIDADE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
